sudo: required
services:
- docker
language: python
python:
- '3.6'
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: j0m1fqgdlOEjxWOVdbSkHa0Tj7idMM6plJqnQCpcuIcwqh83Scs+6wyuF7JZeCXiRHfrZg6X7q4Rfs4ItAsakp9YZEaFdsgyxWow1X2GsIXu3IoDHxc6A+nwTS/GRk/w1tuEnMNYfuHc4HIuF1NYC5RqElsXAZ+iaimEgY8Pqwyr2osyIYl0HgsT3oMG0DD97IihxTaLkTlSHPyjIjJJlOcs6VFnCGRgeKgsdRI87ldvLDz5DLx6q6IcUh3vDWnlZaOvm/0UJaxkvfrNVKW9dLzizweTSpy6WHs5/lTitXIsX6/oxW530AXlB7Ghi9e7ZULvQua0z0ycOunsuTmC9daCNtr4tyvK7Wsn/e2dcUOiDQEIQi7OQ+Y9tNLqaC5XJqkzQ2n92TeTGq3OB8B/bl/u3hIOka1GfGzIwXnklWGQqX4Pa/QiMppt158G3/qshNBITpNkla+zyceAP//xtNpQQjnzA8klYWF0g/uZLK8vIxEJjJeBL4PAuqschMW8RuzwaJmlXH1NEynv3osZWJVR8pf3GTp2TnpOpXOBR8Vc/JmTsQagDJfoy8FgzUDNMK/+92YTHxo6P/yKCV8MnL7vodWySsg0N+SYa7/5Hwxwa6IhsQJHmJTDMoPmdAqwHXvsdw3WMcDUSQOnUEuiBDM6PR5N8E9O9cFUKYCULgk=
  - secure: iYkBZvyusxqLPtUrJi8WyO4vMxIYpw5rXuJAwX7TNYW8RXKZ1/3H2L2o8IxgV6C9s1JLHxD6bJ1kk3cRPt9FcTZxeGQVuzv8aSUPBfjr38ihIY5ovoqL3d8i+GOVl5E3ja6gQ5GJ28WdY3mMyIIWMMtr9oTaSEZw5m30O2y4hMzX7rZ9MwhriIzrhizYyDJwiehJ1qOp2w+BLm/dt3CFtra7KpBndMt4TpSeTk0BSdBVqrOWN18L8qOhmy8OSrITIWNz/rPZ40LssphrPyJC4kJIOiwKxVZQuBmFbbrqfzCaWv7kBV0lLno3Xbyy7Fnwe3jVG0Tke5McZexcl1+bCQTtjKZ9wQhi+DBNBz2vAEOAQQ2LD2SF3m9R0ho0/kl8FTBXl9kk/6+PFv8ZGOgGUjQ5ljmoQWL5GZIgh4tIgRB0XJ5I1KVNjdqCkemUcwXo3gW2VS5TqqPw3k+GuYXIHGUTVNrHgZEx5lzOXZ97oczc1PwX5Ep9QJR1UuHWuulqSSNz4LLAgO0swIGUK4t7SQrO43iQyBrta0Qd/0UDLayb1C4agqzs8zvcYKmJDP+QJL0irAcnCrsI4f5hK/C69C60yRGn+CVIqYuEmMMk2jbYnr/4uBgDV70D9COv4Tz+UuOlypla5MXCxa7rqateCSM7EQbC9Gh1uw1/l38nu5g=
  - secure: KPn0vciIFi/euXJJ8RnW7g/v2fnGEoASr0uQnRNTUsNQVbT8YZzCUVY3PVWQKqJtUhW8Es02ozoEFD6O5/p4cQkSc2eYMBPpJHhj9DnCKxpKgelmC+4NCnzdanmdY1uWkwP9a6AJHvbgpgR1mv6DsgayIUkPYdkKqsjydGdZxxJWEl9KDuMfoxzBQtVxcUqwpfEvOLkgDWF5XXjC9i7BlsZnAlqhE+Gy1P/K71u3wUewI+Nod3iXGaKcCaocHTLiJU3jHvN4ANHs2NLH2fQB3PqA5Jg2AZtLpTH9yFvhY9k2kYbuxrOO15y5M/zC8zk1emRF4wvFwt+PVqpxOvsuvpB52RQ5wUikYOw1Z0br8ZDAlRLJz4idtfgikBMPeDOQWo3GXC3eNg44eHQA39yRICuEUKMHrDtqcbosxpZZqHga9kdnSrqs1W0Ca1BgoZTX9sj8hOMKQYjh078P+78TJJtu37tP+jWGlC9/ww+K4cqTSdbcZwzFXnpsvJJoZUoO9pREpsQ0zKiRIi6q3bcFJFluApTF233AJwOXMa5SKSXu0sfKpSf03yVnZH8OuFA+tDLrvItdLkvPVDO2wXIRBWj/w8NLSz+mQbJnAjV64WBiCWBwZic7iqX0YLVjxUCBBdu0dW1HH2mc4gmZXBD9RTxBl7v8GrD+adA/YSOcunU=
script: make dockerfile
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=gfleury/logstash-oss
- export TAG=`if [ "$TRAVIS_BRANCH" == "es_tsuru" ]; then echo "latest"; else echo
  $TRAVIS_BRANCH ; fi`
- docker build -f build/logstash/Dockerfile-oss -t $REPO:$COMMIT build/elasticsearch
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
