sudo: required
services:
- docker
language: python
python:
- '3.6'
env:
  global:
  - ELASTIC_VERSION=5.2.2
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: woufldsMRH6Futi1cjcmDrf7WCF/45s6J7PJhpmG2bIOMj3crtMGSgASSFGtjFhEzDOXQ566haH6y4p2Yr3rP0c0XAqdb75GQenfXPhp87DMbss/A469iuDOxKdErJ2rtc+Cjm5EIYB3ZHNzQsSbv9E220tAFoi2WehcxB0iNtLnWTGP65ipJsaCjnFJobG3cLJL+F+H97dF4XwpmXZdF2OSZkuxGsPyfRIBHK8VNmiptJAQOwOxHMqfGYyuSDdZS4txGF8zYnQcX6+RWr3K7cCEnDTqD3m+qyLCpMssrFKcZnDwEPGYR8iI/puU+pjR3341JC8im0MbQJT3v9GOpoAleCJjTjj9FQN8wWIkVwz06BhaGz08vp+r8tkrMRPhx7BHSSnvxmm4y2Efda4KeeYG+nIxusbY/MWe5pNdrU/61/y54bu1VP6eJ1TmjZ5tro1j3WIjO0HrUSbQ8MqHkVSXCBxEc1Y4ef4sf4+CN34w5nIt0Up+iKKoaU+A2DEf3qtUXh4yU9QVBYF/EYSv9LHxR6j81CKPYFShIzS0InCsJVcoIdFpq0MfhMj1l5bj5z+fSrTsyE0MZAvzPh4tjODnKUi0LXL5QWIbLtvBgLGS5UH4qP61KcGe62AkDWctowQkiHIM+peU3UAeTXtwfysc7jtqDTblM4aWNfIqcss=
  - secure: D8ReG35/ZKeLLGlIHpBOXlxci6m9bqFDPFeOQZOlQpQkcnY74ZUBmt5w91tMTe0dhiCTi8OZOAgfg7mixf5bC+0/HFGMhV8JVNF6/Fn8rJBIf7S/e3tYQ1Ph75UcxEY2A4SfATNIuVWV4UFXWC/TlEtfbMDQCBjrvbiRc7g/9qxxg5lhKMl30t55LAhyv39wzgdnY+xkmvTKwBuBJvQw8WkZkQ/2Upts4q82P/m8E6NqPLV075KnBoKy2fBcmJDWO6EtcOm1BLwpBFUGCeX7zG7+4v1byVmanaNyizLUICm+u8cD+ofZDxS1DQngUYjPb51mzBTdFTvbiIeyFeAaBZMm8md53q1GdVg9z8NPe48qmMGsVn0/JkaBeHh9hhiK71t6Wmdj/JP+rupaNPSNcjVzqqwoZr9EnFlOmbErnAYodl/zsnW+w5YBdcbqXA642DNwbIuI5LQ0tXXVUq4yC5Q2fOoESqsmCFlsGv7HqIZa4xF7MytCH+DaiQx92KKMgZqySVteoZvRWKtgkE84ppIbr02duCSU66XrPKdrpI+fwwu6KLf4SGiEXdJm7+VaiyhGVxzBwevV3DtumSt6GoW/KBBqOoVILahBeQ8Gd2qkHRY7hY7HWcG0o5Az9xxJjU8v9vTVCsjYHcRV71giLPaDmwu+tj1HR0Cy59dRDt4=
  - secure: dfylyL6bCA4nfGAASvxCfBMCjWjyqFWYMc2I+REkqg/IYEy97uEVgv6Al8hYaRqc6LJRwO83/hEp+qrjXH802QBTHY/ga72yhBDzb9wAVCNEy5AWvLKOfWkK24I8behQJc1raSWoIviS/HBI4H3ZbmOvQwQ/AONGp/h+jQdeOfnoKEsap2j670WR4UxXHADDql52bffypXLxOU77cNUPF6oD5BgihBlWlEEGlmvg00haMT7/z3YhvS2rNGbT0Md50/US+pY5uGoVx9GCjQ3f3c8QwrYLrQBsS4UTxc+WNLPOHUvpHfFf68ZhAHIj/sByepI5yTqDYbIUq+zDbRNlDoH83mvyBsCnfOPatAthzAj+mXSRkMby6S44YT1gplDePK7iMq5K35VS2+xV7/iA2xHosMpvqAn0nSW1izb4L7o/xcGi1Wr5RhLr7P+H2UO0cit/G7AlmRRrxSQmgVcv6jqd2K/NZY1f2PqSH2fkxdxG23Ip4GeIy/EVcZCBnE/04KJalJxhrPi10HvTO0mCbiVPwXfsSZSaMwxTJDdStt5GisYmAEklOgFydX7bk3EmthswECn3UAPEJOfAfo9eb29jDnsNj4WQ92apicCYBxe+stzN/b1/ZiRl7j1tZ+yjA2kAPxP/Rf4Fi/gPvZMC/12z1phSqbbM/9k07o0aL6s=
script: make dockerfile
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=gfleury/logstash-oss
- export TAG=`if [ "$TRAVIS_BRANCH" == "logstash_tsuru" ]; then echo "latest"; else
  echo $TRAVIS_BRANCH ; fi`
- docker build -f build/logstash/Dockerfile-oss -t $REPO:$COMMIT build/logstash
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
